version: "3.7"
services:
  redis:
    image: redis
    container_name: "my_redis"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  postgresql:
    image: "postgres:latest"
    container_name: "my_postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  mongodb:
    image: "mongo"
    container_name: "my_mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: data
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: my_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq/
